import os
import sys
import json
import re

sys.stdout.reconfigure(encoding='utf-8', errors='replace')
PROJECT_ROOT = r'D:\kiarash\kiarash git codes\MirMap&Motive_HeavyPhase_IntermediateV1'
AGENTS_DIR = os.path.join(PROJECT_ROOT, 'agents')
LEDGER_PATH = os.path.join(PROJECT_ROOT, 'MASTER_ANOMALY_LEDGER.txt')

print('\n>>> BEGIN 100x PRECISION FORENSIC PROBE (3/10): SPATIAL PROMPT & ROSBRIDGE TRACING <<<')

# 1. GENERATE THE MASTER ANOMALY LEDGER (As requested by Operator)
print('\n[1/3] GENERATING MASTER ANOMALY LEDGER FOR FINAL REPORT...')
train_json_path = os.path.join(PROJECT_ROOT, 'dataset', 'train.jsonl')
jerk_count = 0
tear_count = 0

try:
    with open(LEDGER_PATH, 'w', encoding='utf-8') as ledger:
        ledger.write("=================================================================\n")
        ledger.write("MASTER ANOMALY LEDGER: KINEMATIC JERKS & TEMPORAL TEARS\n")
        ledger.write("Generated by: Probe 100x Series (Rule 38 Active)\n")
        ledger.write("=================================================================\n\n")
        
        if os.path.exists(train_json_path):
            prev_v, prev_w, prev_frame = None, None, None
            with open(train_json_path, 'r', encoding='utf-8') as f:
                for line_idx, line in enumerate(f):
                    try:
                        data = json.loads(line)
                        action = data.get('ground_truth_action', [0.0, 0.0])
                        v, w = float(action[0]), float(action[1])
                        uid = data.get('id', '')
                        img = data.get('image', '')
                        match = re.search(r'frame_(\d+)', uid)
                        frame = int(match.group(1)) if match else -1
                        
                        # Jerk Logic
                        if prev_v is not None:
                            dv, dw = abs(v - prev_v), abs(w - prev_w)
                            if dv > 0.3 or dw > 0.4:
                                jerk_count += 1
                                sec = frame * 0.025
                                ledger.write(f"[JERK #{jerk_count}] Line: {line_idx+1} | Time: ~{sec:.2f}s | Frame: {frame} | Origin: {img}\n")
                                ledger.write(f"           Speed Jump: [{prev_v:.3f}, {prev_w:.3f}] -> [{v:.3f}, {w:.3f}] (dv:{dv:.3f}, dw:{dw:.3f})\n")
                        
                        # Tear Logic
                        if prev_frame is not None and frame != -1:
                            if frame - prev_frame != 1:
                                tear_count += 1
                                ledger.write(f"[TEAR #{tear_count}] Line: {line_idx+1} | Jump: Frame {prev_frame} --> Frame {frame} (Gap: {frame - prev_frame})\n")
                                ledger.write(f"           Transition ID: {uid}\n")
                        
                        prev_v, prev_w, prev_frame = v, w, frame
                    except Exception: pass
        print(f'  [+] Master Ledger generated at: {LEDGER_PATH}')
        print(f'  [+] Total entries logged: {jerk_count} Jerks, {tear_count} Tears.')
except Exception as e:
    print(f'  [-] Failed to generate Ledger: {e}')

# 2. TRACING SEMANTIC ENTROPY (Spatial VLM Prompt Generators)
print('\n[2/3] TRACING ORIGIN OF SEMANTIC ENTROPY (Spatial Prompt Lack):')
prompt_agents = ['qwen_dataset_formatter.py', 'video_narrator.py']
for agent in prompt_agents:
    path = os.path.join(AGENTS_DIR, agent)
    if os.path.exists(path):
        with open(path, 'r', encoding='utf-8-sig') as f:
            lines = f.readlines()
            for i, line in enumerate(lines):
                # Search for hardcoded strings that make up the prompt
                if ('prompt' in line.lower() or 'instruction' in line.lower()) and ('=' in line or ':' in line):
                    # Only print if it looks like a string assignment
                    if '"' in line or "'" in line:
                        clean_code = line.strip()[:150]
                        print(f'  [*] Found Prompt Generator in {agent} at Line {i+1}:')
                        print(f'      -> Code: {clean_code}')

# 3. TRACING ROSBRIDGE WEBSOCKET CONNECTION
print('\n[3/3] TRACING ROSBRIDGE WEBSOCKET ARCHITECTURE:')
ros_agents = ['launch_session.py', 'mir_command_logger.py']
for agent in ros_agents:
    path = os.path.join(AGENTS_DIR, agent)
    if os.path.exists(path):
        with open(path, 'r', encoding='utf-8-sig') as f:
            lines = f.readlines()
            for i, line in enumerate(lines):
                if 'roslibpy' in line or 'ws://' in line or '9090' in line:
                    print(f'  [*] Found ROSBridge Socket Connection in {agent} at Line {i+1}:')
                    print(f'      -> Code: {line.strip()}')

print('\n>>> PROBE 3/10 COMPLETE. WAITING FOR EXACT PROMPT AND SOCKET ARCHITECTURE. <<<')
